// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOiQduDUUeYSXrpxVszeSZGT6rwfQ33HQ',
    appId: '1:1037991187398:web:5c721e89817b4c59c918c7',
    messagingSenderId: '1037991187398',
    projectId: 'leam-c34ea',
    authDomain: 'leam-c34ea.firebaseapp.com',
    storageBucket: 'leam-c34ea.firebasestorage.app',
    measurementId: 'G-1LCFHS4X9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFnDMk6DiXLjqF0PKFoFXrEXT9ASP8UBU',
    appId: '1:1037991187398:android:6649e46118ef5111c918c7',
    messagingSenderId: '1037991187398',
    projectId: 'leam-c34ea',
    storageBucket: 'leam-c34ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdShk_xecsuvPwGEg9M7tcQOCFhPIHVTg',
    appId: '1:1037991187398:ios:afe4f24ceda30322c918c7',
    messagingSenderId: '1037991187398',
    projectId: 'leam-c34ea',
    storageBucket: 'leam-c34ea.firebasestorage.app',
    iosBundleId: 'com.app.leam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdShk_xecsuvPwGEg9M7tcQOCFhPIHVTg',
    appId: '1:1037991187398:ios:afe4f24ceda30322c918c7',
    messagingSenderId: '1037991187398',
    projectId: 'leam-c34ea',
    storageBucket: 'leam-c34ea.firebasestorage.app',
    iosBundleId: 'com.app.leam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOiQduDUUeYSXrpxVszeSZGT6rwfQ33HQ',
    appId: '1:1037991187398:web:0c73162de9a3f522c918c7',
    messagingSenderId: '1037991187398',
    projectId: 'leam-c34ea',
    authDomain: 'leam-c34ea.firebaseapp.com',
    storageBucket: 'leam-c34ea.firebasestorage.app',
    measurementId: 'G-5SZVQNYH87',
  );

}