// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuR4KUTIop4WyGOwAW3pKPGEFzY1V0III',
    appId: '1:415637342685:web:3c8af1fc352863d23b0e34',
    messagingSenderId: '415637342685',
    projectId: 'leam-dc054',
    authDomain: 'leam-dc054.firebaseapp.com',
    storageBucket: 'leam-dc054.firebasestorage.app',
    measurementId: 'G-ND4656F1BD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYy9VssX7k9ZrsBiFJwxKp2n5s7GGpmvU',
    appId: '1:415637342685:android:34734906ece62d223b0e34',
    messagingSenderId: '415637342685',
    projectId: 'leam-dc054',
    storageBucket: 'leam-dc054.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDot1jFjnLZdAvrmy3EZqe-dPaLXMsKMnQ',
    appId: '1:415637342685:ios:3cf6b297c5d8e6533b0e34',
    messagingSenderId: '415637342685',
    projectId: 'leam-dc054',
    storageBucket: 'leam-dc054.firebasestorage.app',
    iosBundleId: 'com.app.leam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDot1jFjnLZdAvrmy3EZqe-dPaLXMsKMnQ',
    appId: '1:415637342685:ios:3cf6b297c5d8e6533b0e34',
    messagingSenderId: '415637342685',
    projectId: 'leam-dc054',
    storageBucket: 'leam-dc054.firebasestorage.app',
    iosBundleId: 'com.app.leam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuR4KUTIop4WyGOwAW3pKPGEFzY1V0III',
    appId: '1:415637342685:web:a914fdfb1729ec423b0e34',
    messagingSenderId: '415637342685',
    projectId: 'leam-dc054',
    authDomain: 'leam-dc054.firebaseapp.com',
    storageBucket: 'leam-dc054.firebasestorage.app',
    measurementId: 'G-C3VV1MDEC5',
  );
}
